name: Deploy Custom Script Self Runner

on:
  workflow_dispatch:

jobs:

  Terraform-CScript:
    runs-on: ubuntu-latest

    steps:
      - name: Checks-out du repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        run: |
          cd ./Terraform/ConfigRunner       
          terraform init -backend-config="sas_token=${{ secrets.BACKENDSTORAGESASTOKEN }}"

      - name: Terraform Plan
        run: |
          cd ./Terraform/ConfigRunner
          terraform plan \
            -var 'AzureSubscriptionID=${{ secrets.SUBSCRIPTIONID }}' \
            -var 'AzureClientSecret=${{ secrets.CLIENTSECRET }}' \
            -var 'AzureClientID=${{ secrets.CLIENTID }}' \
            -var 'AzureTenandID=${{ secrets.TENANTID }}' \
            -lock=false -out=tf.plan

      - name: Terraform Apply
        run: |
          cd ./Terraform/ConfigRunner
          terraform apply -lock=false "tf.plan"
