name: Lint Terraform

on:
  workflow_dispatch:

jobs:

  Terraform-fmt:
    runs-on: ubuntu-latest
    steps:

      - name: Checks-out du repository
        uses: actions/checkout@v2

      - name: Run terraform fmt check
        run: |
          cd ./Terraform && terraform fmt -check -diff
        id: var_fmt_check

      - name: Error fmt check
        if: ${{ failure() }}
        run: |
          cd ./Terraform && terraform fmt -check -diff 
          
