name: Lint Terraform

on:
  workflow_dispatch:

jobs:

  Terraform-fmt-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out du repository
        uses: actions/checkout@v2

      - name: Terraform fmt check        
        run: |          
          terraform fmt -check -diff ./Terraform
        id: var_fmt_check
      
      - name: Get Timestamp
        if: ${{ failure() }}
        run: |
          echo "::set-output name=today::$(date "+%Y/%m/%d-%Hh-%Mm-%Ss")"
        id: var_timestamp

      - name : Create fmt check issue
        if: ${{ failure() }}
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title: Error fmt check Terraform ${{ steps.var_timestamp.outputs.today }}
          body: |
            ## Fucking Terraform
            Erreur : ${{ steps.var_fmt_check.outputs.stdout }}
          assignees: |
            Pierre-Chesne
          labels: |
            Error lint Terraform



