name: Lint Terraform

on:
  workflow_dispatch:

jobs:

  Terraform-fmt-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out du repository
        uses: actions/checkout@v2

      - name: Terraform fmt check
        run: |          
          terraform fmt -check -diff ./Terraform
        id: var_fmt_check

  Terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out du repository
        uses: actions/checkout@v2

      - name: Terraform Validate
        run: |
          cd ./Terraform
          terraform validate      
      


      




