name: Lint Terraform

on:
  workflow_dispatch:

jobs:

  Terraform-fmt-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out du repository
        uses: actions/checkout@v2

      - name: Terraform fmt check
        run: |          
          terraform fmt -check -diff ./Terraform/Rg
        id: var_fmt_check

  Terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out du repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        run: |
          cd ./Terraform/Rg         
          terraform init -backend-config="sas_token=${{ secrets.BACKENDSTORAGESASTOKEN }}"

      - name: Terraform Validate
        run: |
          cd ./Terraform/Rg
          terraform validate

  Terraform-plan:
    runs-on: ubuntu-latest
    needs:
      - Terraform-fmt-check
      - Terraform-validate
    steps:
      - name: Checks-out du repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        run: |
          cd ./Terraform/Rg         
          terraform init -backend-config="sas_token=${{ secrets.BACKENDSTORAGESASTOKEN }}"

      - name: Terraform Plan
        run: |
          cd ./Terraform/Rg
          terraform plan \
             -var 'AzureSubscriptionID=${{ secrets.SUBSCRIPTIONID }}' \
             -var 'AzureClientSecret=${{ secrets.CLIENTSECRET }}' \
             -var 'AzureClientID=${{ secrets.CLIENTID }}' \
             -var 'AzureTenandID=${{ secrets.TENANTID }}' \
             -lock=false -out=tf.plan
          ls -lisa

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8