name: Test

on:
  workflow_dispatch:

jobs:
  Init-Workflows:
    runs-on: ubuntu-latest

    steps:
        - id: msg
          name: " 👋  - Démarrage du Workflow"
          run : |
            echo " 👋  - Démarrage du Workflow"
    

