name: Test

on:
  workflow_dispatch:

jobs:
  Init-Workflows:
    runs-on: ubuntu-latest

    steps:
        - id: msg
          name: " 👋  - Démarrage du Workflow"
          run : |
            echo " 👋  - Démarrage du Workflow"
            
  
  Build-Terraform:
    runs-on: ubuntu-latest
    needs: Init-Workflows
    
    steps:
      - name: Checks-out du repository
        uses: actions/checkout@v2

      # Install the needed version of Terraform cli
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
    
    
    
    

