name: Test 1

on:
  workflow_dispatch:

jobs:

  Lint-Terraform:
    runs-on: ubuntu-latest
    steps:

      - name: Checks-out du repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        run: |
          cd ./Terraform         
          terraform init -backend-config="sas_token=${{ secrets.BACKENDSTORAGESASTOKEN }}"

      - name: Terraform Validate
        run: |
          cd ./Terraform
          terraform validate

      - name: Run terraform fmt check
        run: |
          terraform fmt -check -diff -recursive ./Terraform
        id: var_fmt_check

      - name: Recuperation de la date
        if: ${{ failure() }}
        run: | 
          echo "::set-output name=today::$(date "+%Y/%m/%d/%H/%M/%S")"
        id: var_date

      - name : Create Issue
        if: ${{ failure() }}
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title: Error Fucking Terraform ${{ steps.var_date.outputs.today }}
          body: |
            ## Fucking Terraform
            Erreur : ${{ steps.var_fmt_check.outputs.stdout }}

          assignees: |
            Pierre-Chesne

          label: |
            Terraform        
      

           